'use server'

const kindnessActs = [
  "Compliment someone today",
  "Donate unused clothes",
  "Write a thank-you note to a friend",
  "Help a neighbor with a chore",
  "Leave a positive review for a local business",
  "Plant a tree or donate to a reforestation project",
  "Pay for the person behind you in line",
  "Volunteer at a local charity",
  "Send a care package to a deployed soldier",
  "Offer to babysit for free for a busy parent",
  "Donate blood",
  "Participate in a charity walk or run",
  "Give old blankets to an animal shelter",
  "Sign up for a bone marrow registry",
  "Become an organ donor",
  "Donate your old cell phone to charity",
  "Help someone carry heavy items",
  "Give up your seat on public transport",
  "Make extra food and share with a neighbor",
  "Pick up litter in your community",
  "Offer to tutor someone in need",
  "Write positive messages on sticky notes and leave them in public places",
  "Pay for someone's meal at a restaurant",
  "Donate books to your local library",
  "Offer to mow a neighbor's lawn",
  "Bake cookies and share them with coworkers",
  "Send flowers to a friend unexpectedly",
  "Help a friend move",
  "Donate to a food bank",
  "Offer to walk a neighbor's dog",
  "Leave quarters at a laundromat",
  "Send a handwritten letter to a family member",
  "Donate school supplies to a local school",
  "Offer to take a photo for tourists",
  "Share your umbrella with someone caught in the rain",
  "Leave a generous tip for your server",
  "Donate to a cause you care about",
  "Offer to help someone with their resume",
  "Bring in donuts or snacks for your office",
  "Help an elderly person with their groceries",
  "Donate toys to a children's hospital",
  "Offer to drive someone without transportation",
  "Pay for someone's parking meter",
  "Help a coworker with a difficult task",
  "Leave a kind note on someone's car",
  "Donate pet food to an animal shelter",
  "Offer to teach a skill you have to others",
  "Give a stranger a compliment",
  "Support a friend's small business",
  "Offer to house-sit for someone",
  "Donate gently used furniture to those in need",
  "Help organize a community event",
  "Offer to edit a friend's essay or article",
  "Bring coffee to a coworker",
  "Help someone who is lost with directions",
  "Offer to pick up groceries for a neighbor",
  "Donate to a disaster relief fund",
  "Help clean up a local park",
  "Offer to lend a tool to someone in need",
  "Share a favorite recipe with a friend",
  "Offer to help someone learn a new language",
  "Donate art supplies to a local school",
  "Help someone with their garden",
  "Offer to take someone's shift at work",
  "Bring a meal to a family in need",
  "Offer to help someone with tech support",
  "Donate to a scholarship fund",
  "Help a friend with their job search",
  "Offer to babysit for free",
  "Share your favorite book with a friend",
  "Help someone move heavy furniture",
  "Offer to mentor someone in your field",
  "Donate to a local theater or arts program",
  "Help a neighbor fix something in their home",
  "Offer to run errands for someone",
  "Share your knowledge by writing a helpful article",
  "Donate to a wildlife conservation fund",
  "Help someone practice for a presentation",
  "Offer to take photos at a friend's event",
  "Bring a treat to your local fire station",
  "Help a friend declutter their home",
  "Offer to drive someone to the airport",
  "Donate to a mental health organization",
  "Help someone set up their new device",
  "Offer to proofread a friend's work",
  "Share your favorite podcast with someone",
  "Help a neighbor with their yard work",
  "Offer to teach a fitness class for free",
  "Donate to a community garden",
  "Help someone assemble furniture",
  "Offer to take care of someone's pet",
  "Share your favorite movie with a friend",
  "Help a coworker meet a deadline",
  "Offer to volunteer at a local event",
  "Donate to a homeless shelter",
  "Help someone learn to ride a bike",
  "Offer to mediate a conflict between friends",
  "Share your musical talents at a community center",
  "Help a friend plan a trip",
  "Offer to organize a friend's closet",
  "Donate to an environmental organization",
  "Help someone study for an exam",
  "Offer to cook dinner for a friend",
  "Share your gardening skills with others",
  "Help a neighbor paint their house",
  "Offer to teach someone how to drive",
  "Donate to a children's charity",
  "Help someone with their taxes",
  "Offer to be a designated driver",
  "Share your workout routine with a friend",
  "Help a coworker with a presentation",
  "Offer to host a study group",
  "Donate to a medical research fund",
  "Help someone with their business plan",
  "Offer to take a friend's pet to the vet",
  "Share your favorite hiking trail with someone",
  "Help a neighbor with snow shoveling",
  "Offer to teach a cooking class",
  "Donate to a literacy program",
  "Help someone with their car maintenance",
  "Offer to organize a community cleanup",
  "Share your photography skills with others",
  "Help a friend with their wedding planning",
  "Offer to tutor a student",
  "Donate to a refugee support organization",
  "Help someone with their social media presence",
  "Offer to lead a workshop in your area of expertise",
  "Share your knitting or crocheting skills",
  "Help a neighbor with their computer issues",
  "Offer to teach a dance class",
  "Donate to a music education program",
  "Help someone with their public speaking skills",
  "Offer to organize a charity fundraiser",
  "Share your language skills by offering translation help",
  "Help a friend with their photography project",
  "Offer to take someone on a nature walk",
  "Donate to an animal rescue organization",
  "Help someone with their writing skills",
  "Offer to host a potluck dinner",
  "Share your travel experiences to help someone plan a trip",
  "Help a neighbor with their home repairs",
  "Offer to teach a yoga class",
  "Donate to a science education program",
  "Help someone with their graphic design needs",
  "Offer to organize a book club",
  "Share your baking skills by making treats for others",
  "Help a friend with their gardening project",
  "Offer to take someone to a cultural event",
  "Donate to a historical preservation society",
  "Help someone with their sewing projects",
  "Offer to lead a meditation session",
  "Share your DIY skills by helping with home projects",
  "Help a neighbor with their landscaping needs",
  "Offer to teach a cooking class",
  "Donate to a community library",
  "Help someone with their social media skills",
  "Offer to lead a workshop in your area of expertise",
]

export async function generateKindnessAct(): Promise<string> {
  const randomIndex = Math.floor(Math.random() * kindnessActs.length)
  return kindnessActs[randomIndex]
}

